
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IMEMOPER = 14;
  public static final int DWORD = 22;
  public static final int DSPACE = 23;
  public static final int ISINGREGOP = 17;
  public static final int DBYTE = 20;
  public static final int RPAREN = 8;
  public static final int STARTTEXT = 6;
  public static final int REG = 25;
  public static final int ROPER = 10;
  public static final int LPAREN = 7;
  public static final int COLON = 4;
  public static final int JOPER = 18;
  public static final int EOL = 2;
  public static final int COMMA = 3;
  public static final int ILABELOPER = 15;
  public static final int EOF = 0;
  public static final int STRLITERAL = 24;
  public static final int IBRANCHOP = 16;
  public static final int error = 1;
  public static final int STARTDATA = 5;
  public static final int IOPER = 13;
  public static final int DASCIIZ = 19;
  public static final int SYSCALL = 12;
  public static final int RSOPER = 11;
  public static final int DHALFWORD = 21;
  public static final int IMM = 26;
  public static final int LABEL = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EOL",
  "COMMA",
  "COLON",
  "STARTDATA",
  "STARTTEXT",
  "LPAREN",
  "RPAREN",
  "LABEL",
  "ROPER",
  "RSOPER",
  "SYSCALL",
  "IOPER",
  "IMEMOPER",
  "ILABELOPER",
  "IBRANCHOP",
  "ISINGREGOP",
  "JOPER",
  "DASCIIZ",
  "DBYTE",
  "DHALFWORD",
  "DWORD",
  "DSPACE",
  "STRLITERAL",
  "REG",
  "IMM"
  };
}

