
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main;

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOT_TEXT = 15;
  public static final int DATA_TYPE = 16;
  public static final int REGISTER = 8;
  public static final int LABEL_DEF = 13;
  public static final int PSOPCODE = 6;
  public static final int LALIOPCODE = 7;
  public static final int OBRACKET = 10;
  public static final int CBRACKET = 11;
  public static final int DOT_DATA = 14;
  public static final int ROPCODE = 2;
  public static final int JOPCODE = 5;
  public static final int IOPCODE = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int IMOPCODE = 4;
  public static final int IMMEDIATE = 9;
  public static final int SYSCALL = 17;
  public static final int LABEL = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ROPCODE",
  "IOPCODE",
  "IMOPCODE",
  "JOPCODE",
  "PSOPCODE",
  "LALIOPCODE",
  "REGISTER",
  "IMMEDIATE",
  "OBRACKET",
  "CBRACKET",
  "LABEL",
  "LABEL_DEF",
  "DOT_DATA",
  "DOT_TEXT",
  "DATA_TYPE",
  "SYSCALL"
  };
}

