package main;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TEXT_SECTION = 12;
  public static final int IMOPCODE = 4;
  public static final int DATA_SECTION = 11;
  public static final int EOL = 13;
  public static final int OBRACKET = 8;
  public static final int REGISTER = 6;
  public static final int CBRACKET = 9;
  public static final int JOPCODE = 5;
  public static final int LABEL = 10;
  public static final int EOF = 0;
  public static final int IMMEDIATE = 7;
  public static final int ROPCODE = 2;
  public static final int error = 1;
  public static final int IOPCODE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ROPCODE",
  "IOPCODE",
  "IMOPCODE",
  "JOPCODE",
  "REGISTER",
  "IMMEDIATE",
  "OBRACKET",
  "CBRACKET",
  "LABEL",
  "DATA_SECTION",
  "TEXT_SECTION",
  "EOL"
  };
}

